name: release
on:
  push:
    branches:
      - main
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i -g @vue/cli
      - run: npm ci --legacy-peer-deps
      - run: vue-cli-service test:unit --passWithNoTests
      - run: npm run build
      - run: semantic-release
        env:
          NPM_TOKEN: ${{secrets.npm_token}}

